sudo: true
language: haskell

git:
  depth: 5

cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  Include:
  - ghc: 8.6.5
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

notifications:
  email: false
    
install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version
  - stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --verbosity warn

script:
  - stack test --system-ghc --verbosity warn
  - stack haddock --verbosity warn --no-haddock-deps synthesis
  # - DOC_DIR=`stack haddock 2>&1 | tail -1 | sed -r -e 's/index.html//g'`
  - DOC_DIR=./.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/doc/html/synthesis/
  - echo $DOC_DIR
  - mkdir -p docs
  - cp -r $DOC_DIR/* ./docs

# can I just kinda cram this on?
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: master
    local_dir: docs
