# generated by cabal2nix 2.15.0

# error: cannot auto-call a function that has an argument without a default value ('base')

{ base, bytestring, containers, criterion
, ghc-lib-parser, hashable, haskell-src-exts, hasktorch, hint
, hpack, hslogger, HUnit, optparse-applicative, prettyprinter
, random, stdenv, store, tasty, tasty-hspec, tasty-hunit
, unordered-containers
}:
stdenv.mkDerivation {
  pname = "synthesis";
  version = "0.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    base bytestring containers ghc-lib-parser hashable haskell-src-exts
    hasktorch hint hslogger optparse-applicative prettyprinter random
    store unordered-containers
  ];
  libraryToolDepends = [ hpack ];
  executableHaskellDepends = [
    base containers ghc-lib-parser haskell-src-exts hasktorch hint
    random unordered-containers
  ];
  testHaskellDepends = [
    base containers ghc-lib-parser haskell-src-exts hasktorch hint
    HUnit random tasty tasty-hspec tasty-hunit unordered-containers
  ];
  benchmarkHaskellDepends = [
    base containers criterion ghc-lib-parser haskell-src-exts hasktorch
    hint random unordered-containers
  ];
  prePatch = "hpack";
  homepage = "https://github.com/tycho01/synthesis#readme";
  description = "typed neural program synthesis";
  license = stdenv.lib.licenses.mit;
}
