name: synthesis
version: '0.0.0'
github: "tycho01/synthesis"
license: MIT
author: "Kiara Grouwstra"
maintainer: "Kiara Grouwstra"
synopsis: typed neural program synthesis
description: code-base for my UvA MSc AI thesis on typed neural program synthesis
category: Machine Learning

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options:
  - -Wall
  - -rtsopts
  - -threaded
  - -with-rtsopts=-N

default-extensions:
  - LambdaCase
  - ScopedTypeVariables
  - UnicodeSyntax
  - RankNTypes

dependencies:
  - base
  - haskell-src-exts # ==1.23.0
  - hint
  - containers
  - unordered-containers
  - ghc-lib-parser==8.8.1
  - random
  # - proto-lens-protoc==0.6.0.0
  - tensorflow # ==0.2.0.1
  - tensorflow-core-ops # ==0.2.0.1
  - tensorflow-logging # ==0.2.0.1
  - tensorflow-opgen # ==0.2.0.1
  - tensorflow-ops # ==0.2.0.1
  - tensorflow-proto # ==0.2.0.1
  # - tensorflow-mnist # ==0.1.0.0
  # - tensorflow-mnist-input-data # ==0.2.0.1
  - tensorflow-records # ==0.1.0.0
  - tensorflow-records-conduit # ==0.1.0.0
  - tensorflow-test # ==0.2.0.1

library:
  dependencies:
  - hashable
  - hslogger
  - bytestring
  - prettyprinter
  - store==0.7.2
  - optparse-applicative
  source-dirs: library

executables:

  generator:
    source-dirs: generator
    main: Main.hs
    dependencies:
    - synthesis

  synthesizer:
    source-dirs: synthesizer
    main: Main.hs
    dependencies:
    - synthesis

benchmarks:
  synthesis-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - synthesis
    - criterion

tests:
  synthesis-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - synthesis
    - tasty
    - tasty-hspec
    - HUnit
    - tasty-hunit
