# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: synthesis
version: '0.0.0'
github: "githubuser/synthesis"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: synthesis is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - template-haskell
  - haskell-src-exts
  - ghc-lib-parser
  - QuickCheck
  - hint
  - random
  - transformers
  source-dirs: library

executables:
  synthesis:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - synthesis
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  synthesis-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - synthesis
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  synthesis-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - synthesis
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
