name: synthesis
version: '0.0.0'
github: "tycho01/synthesis"
license: MIT
author: "Kiara Grouwstra"
maintainer: "Kiara Grouwstra"
synopsis: typed neural program synthesis
description: code-base for my UvA MSc AI thesis on typed neural program synthesis
category: Machine Learning

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

default-extensions:
  - LambdaCase
  - ScopedTypeVariables
  # - UnicodeSyntax
  # - QuasiQuotes
  # - TemplateHaskell

dependencies:
  - base
  - haskell-src-exts==1.23.0
  - hint
  - QuickCheck
  - containers
  - unordered-containers
  # - ghc-lib-parser==8.8.1

library:
  dependencies:
  - template-haskell
  # - ghc-lib==8.8.1
  - random
  - transformers
  - hashable
  - hslogger
  # - dump  # needs older haskell-src-exts
  - bytestring
  - prettyprinter
  source-dirs: library

executables:
  synthesis:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - synthesis
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  synthesis-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - synthesis
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  synthesis-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - synthesis
    - tasty
    - tasty-hspec
    - HUnit
    - tasty-hunit
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
