name: synthesis
version: '0.0.0'
github: "tycho01/synthesis"
license: MIT
author: "Kiara Grouwstra"
maintainer: "Kiara Grouwstra"
synopsis: typed neural program synthesis
description: code-base for my UvA MSc AI thesis on typed neural program synthesis
category: Machine Learning

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options:
  - -Wall
  - -rtsopts
  - -threaded
  - -with-rtsopts=-N

default-extensions:
  - LambdaCase
  - ScopedTypeVariables
  - UnicodeSyntax
  - RankNTypes

dependencies:
  - base
  - haskell-src-exts==1.23.0
  - hint
  - containers
  - unordered-containers
  - ghc-lib-parser==8.8.1

library:
  dependencies:
  - template-haskell
  - random
  - hashable
  - hslogger
  - bytestring
  - prettyprinter
  - store==0.7.2
  source-dirs: library

executables:
  synthesis:
    source-dirs: generator
    main: Main.hs
    dependencies:
    - synthesis
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
  synthesizer:
    source-dirs: synthesizer
    main: Main.hs
    dependencies:
    - synthesis

benchmarks:
  synthesis-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - synthesis
    - criterion

tests:
  synthesis-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - synthesis
    - tasty
    - tasty-hspec
    - HUnit
    - tasty-hunit
